name: build-gcc-image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit sha to build from'
        required: false
        default: '46666b9bde5903d80ad8a30f5e7ecb6fc4208290'
      version:
        description: 'Version corresponding to the chosen tag'
        required: false
        default: '14'

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: Docker-hub-Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build-and-push-image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: gcc/Dockerfile
          push: true
          tags: dglaeser/compiler-images:gcc-${{ github.event.inputs.version }}
          target: gcc
          build-args: |
            TAG=${{ github.event.inputs.tag }}
